### ISSUE TITLE
TRAEFIK_MAPPER_FILTER_WWW_MIDDLEWARE doesn't work

### ISSUE THREAD

**Issue by JVT038** [beaussan/traefik-http-provider-mapper#2]
I set the variable `TRAEFIK_MAPPER_FILTER_WWW_MIDDLEWARE` to true, but it doesn't work.
The JSON response from this container is as follows:
```json
{
    "http": {
        "routers": {
            "cld3ldarf0000r39t9mmpjaxs-3000-/-secure": {
                "entrypoints": [
                    "https"
                ],
                "rule": "Host(`app.domain.com`) && PathPrefix(`/`)",
                "service": "cld3ldarf0000r39t9mmpjaxs-3000",
                "priority": 2,
                "tls": {
                    "certresolver": "dns-cloudflare"
                },
                "middlewares": [
                    "chain-basic@file"
                ]
            },
            "cld3ldarf0000r39t9mmpjaxs-3000-/-secure-www": {
                "entrypoints": [
                    "https"
                ],
                "rule": "Host(`app.domain.com`) && PathPrefix(`/`)",
                "service": "cld3ldarf0000r39t9mmpjaxs-3000",
                "priority": 2,
                "tls": {
                    "domains": {
                        "main": "app.domain.com"
                    }
                },
                "middlewares": [
                    "redirect-to-non-www",
                    "chain-basic@file"
                ]
            }
        },
        "services": {
            "cld3ldarf0000r39t9mmpjaxs-3000": {
                "loadbalancer": {
                    "servers": [
                        {
                            "url": "http://cld3ldarf0000r39t9mmpjaxs:3000"
                        }
                    ]
                }
            }
        },
        "middlewares": {
            "redirect-to-https": {
                "redirectscheme": {
                    "scheme": "https"
                }
            },
            "redirect-to-http": {
                "redirectscheme": {
                    "scheme": "http"
                }
            }
        }
    }
}
```
As you can see, the `"redirect-to-non-www" middleware is still included, despite the environment variable.
My `docker-compose.yml`:
```yml
  traefik-http-provider-mapper:
    image: beaussan/traefik-http-provider-mapper
    restart: unless-stopped
    environment:
      # Required, the address of the coolify server
      - TRAEFIK_MAPPER_BASE_ENDPOINT=http://coolify:3000/webhooks/traefik/main.json

      # All the following are optional

      # Replace the web entrypoint with what is provided (eg http here)
      - TRAEFIK_MAPPER_NEW_HTTP_ENTRYPOINT=http
      # Replace the websecure entrypoint with what is provided (eg https here)
      - TRAEFIK_MAPPER_NEW_HTTPS_ENTRYPOINT=https
      # Replace the certificate store (letsencrypt) with what is provided (eg cert here)
      - TRAEFIK_MAPPER_NEW_CERT_RESOLVER=dns-cloudflare

      # Adds this middleware to all routes, ex middlewareName@file for a file base middleware, middlewareName@docker for a docker base middleware
      - TRAEFIK_MAPPER_ADD_MIDDLEWARE_NAME=chain-basic@file

      # Ignore routers for the middlewares. This can be usefull to filter out some domains
      - TRAEFIK_MAPPER_IGNORE_MIDDLEWARE_SITES=app.domain.com

      # Remove coolify itself from the list of services
      - TRAEFIK_MAPPER_FILTER_COOLIFY=true
      # Remove www redirect middleware from the list of middlewares
      - TRAEFIK_MAPPER_FILTER_WWW_MIDDLEWARE=true
      # Remove all http routes from the list of routes
      - TRAEFIK_MAPPER_FILTER_HTTP_ROUTERS=true
      # Remove all www routes from the list of routes
      - TRAEFIK_MAPPER_FILTER_WWW_ROUTERS=true

    networks:
      - coolify-infra
      - traefik
```
